CLASS zbp_i_manualclass_byd_mat DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
      INTERFACES if_oo_adt_classrun.

  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS ZBP_I_MANUALCLASS_BYD_MAT IMPLEMENTATION.
ENDCLASS.
